# Opens a PR when a new monarchmoneycommunity (or other dependency) release is out

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[pip] "
      include: "scope"
    labels:
      - "pip"
      - "dependencies"
